CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    sort_order INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS clients (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    sort_order INT DEFAULT 0,
    priority VARCHAR(20) DEFAULT NULL,
    progress_percent DECIMAL(5,2) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    assigned_to INT NOT NULL,
    client_id INT DEFAULT NULL,
    priority VARCHAR(20) NOT NULL DEFAULT 'Normal',
    due_date DATE DEFAULT NULL,
    status VARCHAR(20) DEFAULT 'pending',
    parent_id INT DEFAULT NULL,
    order_index INT DEFAULT 0,
    FOREIGN KEY (assigned_to) REFERENCES users(id),
    FOREIGN KEY (parent_id) REFERENCES tasks(id) ON DELETE CASCADE,
    FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE IF NOT EXISTS comments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    task_id INT NOT NULL,
    user_id INT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS comment_files (
    id INT AUTO_INCREMENT PRIMARY KEY,
    comment_id INT NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    original_name VARCHAR(255) DEFAULT NULL,
    FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS work_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    log_date DATE NOT NULL,
    clock_in DATETIME NOT NULL,
    clock_out DATETIME DEFAULT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS client_id INT DEFAULT NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS priority VARCHAR(20) NOT NULL DEFAULT 'Normal';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS recurrence VARCHAR(50) DEFAULT 'none';
ALTER TABLE tasks MODIFY due_date DATE DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255) NOT NULL AFTER username;
ALTER TABLE users ADD COLUMN IF NOT EXISTS sort_order INT DEFAULT 0;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS sort_order INT DEFAULT 0;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS priority VARCHAR(20) DEFAULT NULL;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS progress_percent DECIMAL(5,2) DEFAULT NULL;
